# Generated by Django 4.1.7 on 2023-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='foto_nota',
        ),
        migrations.AddField(
            model_name='nota',
            name='descricao',
            field=models.CharField(default='material', max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor_material',
            field=models.DecimalField(decimal_places=4, max_digits=1000),
        ),
    ]
